version: 2

references:
  ## Cache
  cahce_key: &cahce_key
    key: cache-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cahce_key
  save_cache: &save_cache
    save_cache:
      <<: *cahce_key
      paths:
        - ~/.gradle

  ## Workspace
  workspace: &workspace
    ~/workspace

  ## Docker images configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  build_debug:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - *save_cache
      - run:
          name: Build Test(Debug)
          command: ./gradlew :app:assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk

workflows:
  version: 2
  workflow:
    jobs:
      - build_debug
